<?php

namespace BingAds\CampaignManagement;

/**
 * Defines the possible types of analytics that campaigns in an account can use.
 * @link http://msdn.microsoft.com/en-us/library/gg985295(v=msads.80).aspx AnalyticsType Value Set
 */
final class AnalyticsType
{
    /** Enables the collection of analytics data for campaigns in the account. You can collect conversions data, revenue generated by conversions, costs (expenses) associated with conversions, and track site-visitor activity that leads to conversions. */
    const Enabled = 'Enabled';

    /** Disables the collection of analytics data for campaigns in the account. */
    const Disabled = 'Disabled';

    /** Provisioning of new campaign-level conversion tracking scripts is no longer supported. The SetAnalyticsType operation will fail. If you had provisioned this analytics type previously and are still using the corresponding scripts, you can use Disabled and Enabled to toggle off and on the tracking of conversion data. */
    const CampaignLevel = 'CampaignLevel';
}
